### ISSUE TITLE
Support ember-cli >= 3.2.0

### ISSUE THREAD

**Issue by jacobq** [felixrieseberg/ember-electron#353]
I haven't finished debugging so can't prove that this problem is related to ember-electron, but when I upgraded from ember-cli 3.1.4 to 3.2.0 I now get an error when running `ember electron:test --server`: `TypeError: testem.setDefaultOptions is not a function`. This appears to be because we are using an old version (1.x) of testem. Even though older versions of ember-cli were using testem 2.x they evidently hadn't been using portions of the API that were new in 2.x.

When I force `ember-electron` to use testem v2.2.0 (instead of 1.18.5) using yarn:
```
"resolutions": {
    "ember-electron/**/testem": "2.2.0"
  },
```
then this error goes away, but it also breaks things. (Breaking changes? :man_shrugging: What are those? :smile:)
It seems that with ember-cli v3.2.0 the `TestTask` now uses [`setDefaultOptions`](https://github.com/ember-cli/ember-cli/blob/v3.2.0/lib/tasks/test.js#L18), which was not [part of the 1.x API](https://github.com/testem/testem/blob/v1.18.5/lib/api.js).

What would it take to upgrade testem from 1.x to 2.x? Is there some reason we are intentionally staying with 1.x?

**Comment by jacobq** [comment]
The list of [breaking changes](https://github.com/testem/testem/releases/tag/v2.0.0) looks rather short & simple: we have higher minimum node versions already and don't appear to be using the `all-test-results` event. So why did it break when I forced a 2.x version? (I saw something like "Not found: /9356/tests/index.html?hidepassed" in the electron test window)

**Comment by felixrieseberg** [comment]
If it works for you, let's upgrade it - and fix things as they come in. Want to just make a PR?

**Comment by jacobq** [comment]
Before making the change I want to make sure and empty project will still build and test.

**Comment by jacobq** [comment]
@felixrieseberg I took a few minutes to look at this again this morning. I think upgrading `testem` to 2.x is fine so will make a PR for that shortly. Unfortunately, there seems to be a bigger issue here. Upgrading `ember-cli` [from 3.1 to 3.2](https://github.com/ember-cli/ember-cli/releases/tag/v3.2.0) seems to be what's breaking things -- perhaps because of [this testem format change](https://github.com/ember-cli/ember-cli/pull/7560). 
See [this junk demonstration app](https://github.com/jacobq/ee-testem/branches)

**Comment by jacobq** [comment]
OK, so I took a stab at this [here](https://github.com/felixrieseberg/ember-electron/pull/354). 
I'm trying to test it out with my junk app. Can I use `ember install ember-electron@jacobq/ember-electron.git#testem-update` or will that create problems? So far it seems to have the same problem with e-cli 3.2.

**Comment by jacobq** [comment]
The change that breaks it for us appears to be here: https://github.com/ember-cli/ember-cli/commit/ebab6cbf7503929859eb36eff2c5aa3d9edb5a4d

**Comment by bendemboski** [comment]
Consuming app's
