### PR TITLE
Support ember cli 3.2

### LINKED ISSUE #353: Support ember-cli >= 3.2.0
I haven't finished debugging so can't prove that this problem is related to ember-electron, but when I upgraded from ember-cli 3.1.4 to 3.2.0 I now get an error when running `ember electron:test --server`: `TypeError: testem.setDefaultOptions is not a function`. This appears to be because we are using an old version (1.x) of testem. Even though older versions of ember-cli were using testem 2.x they evidently hadn't been using portions of the API that were new in 2.x.

When I force `ember-electron` to use testem v2.2.0 (instead of 1.18.5) using yarn:
```
"resolutions": {
    "ember-electron/**/testem": "2.2.0"
  },
```
then this error goes away, but it also breaks things. (Breaking changes? :man_shrugging: What are those? :smile:)
It seems that with ember-cli v3.2.0 the `TestTask` now uses [`setDefaultOptions`](https://github.com/ember-cli/ember-cli/blob/v3.2.0/lib/tasks/test.js#L18), which was not [part of the 1.x API](https://github.com/testem/testem/blob/v1.18.5/lib/api.js).

What would it take to upgrade testem from 1.x to 2.x? Is there some reason we are intentionally staying with 1.x?

### PR DESCRIPTION
**Pull request by jacobq**
This is a cleaned-up version of https://github.com/felixrieseberg/ember-electron/pull/354
Please review; I'd love for ember-cli v3.2 support to land.

Closes #353

### CODE REVIEW

**Comment by jacobq** [comment]
Uh oh, any idea why TravisCI isn't picking this up?

File: node-tests/acceptance/end-to-end-test.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ describe('end-to-end', function() {
       return ember('new', 'ee-test-app').then(() => {
         process.chdir('ee-test-app');
 
-        return ember('install', `ember-electron@${path.join(packageTmpDir, 'package')}`);
+        return ember('install', `ember-electron@file:${path.join(packageTmpDir, 'ember-electron.tgz')}`);
```
[the remark this answers is not in the document]
Comment (stopdropandrew) [reply node-tests/acceptance/end-to-end-test.js]: Yes, because npm >5 symlinks packages instead via file which was causing module resolution to fail. https://medium.com/@alex_young/npm-5-and-file-urls-3c3631f7367c

[the remark this answers is not in the document]
Comment (bendemboski) [reply node-tests/acceptance/end-to-end-test.js]: Ah, gotcha. Then let's re-tar the package directory into a new temp tarball and use that so it picks up the version-cache-busting.

[the remark this answers is not in the document]
Comment (jacobq) [reply node-tests/acceptance/end-to-end-test.js]: @bendemboski I'm not sure how to do that. Is that something you or @stopdropandrew would be willing to do? (I'm done `git push -f`ing now -- fixed `.travis.yml`)

[the remark this answers is not in the document]
Comment (bendemboski) [reply node-tests/acceptance/end-to-end-test.js]: I think something like this:

```javascript
return ember('new', 'ee-test-app').then(() => {
  process.chdir('ee-test-app');

  return run('tar', ['-czf', 'ember-electron-cachebust.tgz', '-C', packageTmpDir, 'package']);
}).then(() => {
  return ember('install', `ember-electron@file:${path.join(packageTmpDir, 'ember-electron-cachebust.tgz')}`);
});
```

[the remark this answers is not in the document]
Comment (jacobq) [reply node-tests/acceptance/end-to-end-test.js]: So we're talking about code [in `node-tests/acceptance/end-to-end-test.js`](https://github.com/jacobq/ember-electron/blob/support-ember-cli-3.2/node-tests/acceptance/end-to-end-test.js#L56), right?
Sorry, I think I'm not following you guys. Why do we need to make a second tarball instead of just using the first? Are they different?

[the remark this answers is not in the document]
Comment (bendemboski) [reply node-tests/acceptance/end-to-end-test.js]: Yes, that's correct. The reason I think we need to do it is because [here](https://github.com/jacobq/ember-electron/blob/support-ember-cli-3.2/node-tests/acceptance/end-to-end-test.js#L53-L62) we package up the app, then untar it so we can change the version in `package.json`. If we don't do that, then it would have the same version as the latest released version of `ember-electron.

At least when I wrote this, `yarn` would look at the version in `package.json`, and if it had a cached version of `ember-electron` with the same version, it would use the cached version and ignore the tarball.

The cached version could be the latest release installed into some other node project somewhere from the npm registry, or a previous version of the local package, like if you're doing local development and run the tests, then make a change, then run the same tests. So it was very problematic.

Perhaps this behavior doesn't currently happen with `npm`, and maybe not even with `yarn` any more, but it still seems sketchy to install a package from a tarball whose version exactly matches that package's version in the npm registry -- just asking for some caching behavior to screw us.

So that's why after packaging it up, we untar it and change the version.

File: .travis.yml [hunk 2]
```diff
@@ -1,13 +1,20 @@
...
+  - "10"
 
 sudo: false
+dist: trusty
 
-node_js:
-  - "6.0"
-  - "7.0"
+addons:
+  chrome: stable
```
Comment (felixrieseberg) [inline .travis.yml]: I had no idea you could do that 👏

Comment (jacobq) [reply .travis.yml]: [Yup](https://docs.travis-ci.com/user/chrome), but I only knew from riding the [coattails of ember-cli](https://github.com/ember-cli/ember-cli/pull/7161).

File: node-tests/acceptance/end-to-end-test.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (jacobq) [reply node-tests/acceptance/end-to-end-test.js]: OK, I think I get it now. We only use the extracted+modified contents of that tarball, but now we're using it directly, which may not be reliable due to potential cache issues.  I still have a couple questions though:
* Would you be opposed to this code being added in the same section where the package is packed, unpacked, and modified? (It makes sense to me to do it there even though one could argue that since it's only used in the `with npm` test right now we shouldn't do it until needed.)
* I know [`yarn pack` compresses the archive](https://yarnpkg.com/lang/en/docs/cli/pack/) and `.tgz`/`.tar.gz` is common, but since we're just making a temporary archive locally that we're going to immediately read back, I would prefer to just use `tar` ([`npm install` appears to support this](https://docs.npmjs.com/cli/install)) for performance / efficiency.

**Comment by jacobq** [comment]
Uh oh, looks like I just went from all green to all red with just a couple lines of code (#skillz). The error message is confusing to me though. Is this because of my changes or because of a transient npm/yarn infrastructure problem? e.g.
* https://ci.appveyor.com/project/felixrieseberg/ember-electron/build/1.0.228/job/ud719hqk9dtuq8f0?fullLog=true#L368
* https://travis-ci.org/felixrieseberg/ember-electron/jobs/403080377#L1284

**Comment by jacobq** [comment]
AppVeyor: only node 6.x passes, Travis: all except node 6.x pass. I can't make this stuff up :scream: :sob: :laughing:

**Comment by jacobq** [comment]
Any idea what is causing [this `apt` issue](https://travis-ci.org/felixrieseberg/ember-electron/jobs/403172894#L582)? I suppose I can try escaping / quoting `g++-4.8` as [that may be a problem](https://stackoverflow.com/questions/30946960/the-command-sudo-apt-get-install-python-dev-python3-dev-failed-and-exited-wit#30950169), but why does it seem intermittent (e.g. only failed on node 10 job)?

**Comment by jacobq** [comment]
More [crazy-making](https://travis-ci.org/felixrieseberg/ember-electron/jobs/403201676#L961):
```
Missing npm packages: 
Package: ember-electron
  * Specified: file:///tmp/tmp-5597c9HY8hfVEyIR/ember-electron-cachebust.tar
  * Installed: ../../tmp-5597c9HY8hfVEyIR/ember-electron-cachebust.tar
```

**Comment by jacobq** [comment]
Where does this [`⠋ cleaning up⠋ cleaning up`](https://travis-ci.org/felixrieseberg/ember-electron/jobs/403218031#L736) junk come from? [`ember-cli`](https://github.com/ember-cli/ember-cli/blob/689bdbfee75ef92a33a86466669062bfb7507531/lib/models/builder.js#L183)? `yarn` (but we set `yarn config set no-progress`)?

**Comment by bendemboski** [comment]
It's `ember-cli` -- when it finished building it prints `cleaning up...` -- you can see it by just running `ember build`

**Comment by jacobq** [comment]
OK, [found](https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L763) [it](https://github.com/ember-cli/console-ui). Seems like it's making a progress spinner though, which tends to clutter the output in CI. I would've thought that's automatically disable when `CI` env var is present.

**Comment by jacobq** [comment]
Same weirdness w/ `.tgz` :cry: Anyone know what's going on? This message is coming from `ember-cli` I think, not `npm` so maybe I need to check into that logic? (but "it worked before", which is the part that's killing me).
```
Missing npm packages: 
Package: ember-electron
  * Specified: file:../../tmp-5702nftN66mbim4B/ember-electron-cachebust.tgz
  * Installed: file:/tmp/tmp-5702nftN66mbim4B/ember-electron-cachebust.tgz
```

**Comment by bendemboski** [comment]
Look like a relative/absolute path problem. Try using `path.join()` instead of `path.resolve()`?

**Comment by jacobq** [comment]
@bendemboski I [started with `.join` and changed to `.resolve`](https://github.com/jacobq/ember-electron/commit/f0a38015cc66f86936cdafc1c5dae355191801cf) in hopes of fixing :joy:

**Comment by jacobq** [comment]
I am tempted to just set [`SKIP_DEPENDENCY_CHECKER `](https://github.com/quaertym/ember-cli-dependency-checker/blob/master/lib/dependency-checker.js#L39) in the CI env vars 🤥

**Comment by jacobq** [comment]
...40 CI builds later... I have a good feeling about this 😅

**Comment by jacobq** [comment]
@bendemboski Would you mind taking another look? I've implemented the change you requested (cache-busting tar ball) and believe I've worked-out the snags encountered along the way. In short:

* [`ember-cli-dependency-checker`](https://github.com/quaertym/ember-cli-dependency-checker) has a [bug](https://github.com/quaertym/ember-cli-dependency-checker/issues/89) that causes it to mistakenly report that a package installed via tar ball is not satisfying the specified version (e.g. due to equivalent but not identically represented paths).
* I submitted a [patch PR](https://github.com/quaertym/ember-cli-dependency-checker/pull/90) to fix this and temporarily changed our test code to use that fork of `ember-cli-dependency-checker`.
* An unidentified problem with `npm` version 4 and earlier seems to prevent the installation from tar ball or verification of correctly installed dependencies from succeeding. Since `npm` 6 supports `node` 6 I've modified the CI configuration files to use `npm` 6 in the `node` 6 jobs (keeping the default versions for 8 [npm@5] and 10 [npm@6]).

**Comment by stopdropandrew** [comment]
Looks good to me, thanks for the persistence this one had my head spinning.

**Comment by jacobq** [comment]
@stopdropandrew You betcha (as we are accused of saying here in MN). Thanks for your help illuminating the bizarre `npm` sym-link/require behavior. Teamwork fo show 🥇

**Comment by jacobq** [comment]
Whoops, looks like my last squash [doesn't get the latest `ember-cli-dependency-checker`](https://ci.appveyor.com/project/felixrieseberg/ember-electron/build/1.0.255/job/7lxw9gf3kcnwejhm#L1912).

**Comment by jacobq** [comment]
Everything was passing then all I did was change from pinning `ember-cli-dependency-checker` to my fork commit back to using the release since the patch was merged, and now [the bug is back](https://ci.appveyor.com/project/felixrieseberg/ember-electron/build/1.0.262/job/94fiu237fkjbf093#L737). :sob:

File: .appveyor.yml [hunk 3]
```diff
@@ -8,11 +8,14 @@ environment:
...
 cache:
+  - '%APPDATA%\npm-cache -> package.json' # Only load this from cache if package.json is unchanged
   - '%LOCALAPPDATA%\Yarn'
   - '%USERPROFILE%\.electron'
 
 install:
   - ps: Install-Product node $env:nodejs_version $env:platform
+  - cmd: IF "%nodejs_version%"=="6" npm install -g npm@6
+  - npm --version
   - npm install yarn -g
```
Comment (jacobq) [inline .appveyor.yml]: If we care, we can take this out now since [AppVeyor ships with yarn 1.7.0](https://www.appveyor.com/updates/2018/06/08/).

File: node-tests/acceptance/end-to-end-test.js [hunk 4]
```diff
@@ -75,7 +75,7 @@ describe('end-to-end', function() {
       let { name: tmpDir } = tmp.dirSync();
       process.chdir(tmpDir);
 
-      return ember('new', 'ee-test-app', '--yarn').then(() => {
+      return ember('new', 'ee-test-app', '--yarn', '--skip-git', '--no-welcome').then(() => {
```
Comment (jacobq) [inline node-tests/acceptance/end-to-end-test.js]: I forgot to mention this in the commit message, but I took the liberty of adding these parameters here since they shouldn't hurt anything (we're not using the git repository created for the new app nor the welcome page), and skipping these should improve test performance a little bit (less file I/O by skipping repo and fewer messages cluttering the log by not having the welcome page package installed).

File: node-tests/acceptance/end-to-end-test.js [hunk 5]
```diff
@@ -94,10 +94,16 @@ describe('end-to-end', function() {
...
-      return ember('new', 'ee-test-app').then(() => {
+      return ember('new', 'ee-test-app', '--skip-git', '--no-welcome').then(() => {
         process.chdir('ee-test-app');
-
-        return ember('install', `ember-electron@file:${path.join(packageTmpDir, 'ember-electron.tgz')}`);
+        // FIXME: This ember-cli-dependency-checker stuff shouldn't be necessary
+        const packageJsonFileWithPath = path.join(process.cwd(), 'package.json');
+        const packageJson = readJsonSync(packageJsonFileWithPath);
+        //packageJson.devDependencies['ember-cli-dependency-checker'] = '^2.2.1';
+        packageJson.devDependencies['ember-cli-dependency-checker'] = 'quaertym/ember-cli-dependency-checker#^2.2.1';
```
Comment (jacobq) [inline node-tests/acceptance/end-to-end-test.js]: If someone could explain it to me, I'd love to know why the commented-out line did not work but this one does. They should be equivalent since that is the main/canonical repository for this addon. It seems like an `npm` bug, but I don't want to investigate it further as it has already been too much of a time sink.

File: .appveyor.yml [hunk 6]
```diff
@@ -1,15 +1,23 @@
 platform:
 - x64
+
 environment:
-  nodejs_version: "6"
```
Comment (jacobq) [inline .appveyor.yml]: As much as I like being thorough and testing all LTS & current node releases, this does blow up the test time. Since we are doing all 3 on Travis (in parallel FTW) we could probably go back to just testing minimum supported node version on AppVeyor.

**Comment by jacobq** [comment]
I just pushed a commit to try taking the `ember-cli-dependency-checker` hack out to see if it works like it should now. (Hoping it was a transient npm & caching thing, though I suspect it will fail.)

**Comment by bendemboski** [comment]
Looks good to me overall. Two additional items that you can decide whether to address now or not:

1. `testem-electron.js` was originally based off of `testem.js` in the `ember-cli` app blueprint. It's been updated in some minor cosmetic ways, so we might consider updating `testem-electron.js` both at the root of the repo and in `blueprints/` to match.
2. `ember-cli` has moved to a single `.eslintrc` as the root of the app since `overrides` are now supported, but `ember-electron`'s blueprint is still creating `.eslintrc` files in subdirectories. It would take a little doing to make `ember-electron`'s blueprint modify the root `.eslintrc`, but shouldn't be too bad...but I'd also be happy getting this filed as a separate issue to address later since this PR has already been such an adventure!

**Comment by jacobq** [comment]
@bendemboski I'll take another peek at that to see if anything looks out-of-date/sync. When I looked before I think I was just checking that [the breaking change regarding `args`](https://github.com/ember-cli/ember-cli/pull/7560) didn't affect it. Regarding 2, earlier today I created [an issue for ESlint improvement](https://github.com/felixrieseberg/ember-electron/issues/357), and I think I'd this would fit nicely into a separate PR that closes that.

**Comment by jacobq** [comment]
Oh, cool, it sounds like the [`--headless` option may work for electron](https://github.com/electron/electron/issues/228#issuecomment-359385793). We might be able to drop the whole `Xvfb` work-around then.

File: testem-electron.js [hunk 7]
```diff
@@ -1,14 +1,29 @@
...
-  'launch_in_dev': [
+  launch_in_dev: [
     'Electron',
   ],
+  browser_args: {
+    Electron: {
+      ci: [
+        // --no-sandbox may be needed when running inside a container
+        process.env.CI ? '--no-sandbox' : null,
+        '--headless',
```
Comment (jacobq) [inline testem-electron.js]: This doesn't seem to work. e.g. `ember electron --- --headless` still launches a visible window.

**Comment by jacobq** [comment]
:rocket: ?

**Comment by bendemboski** [comment]
🎉 nice work @jacobq! Perfect timing for me -- I'm just getting to upgrading my Electron app to the latest Ember, so thanks a bunch!

**Comment by bendemboski** [comment]
Hey @felixrieseberg can you cut a new release so this code is out there for folks wanting to run against `ember-cli@3.2`?

**Comment by felixrieseberg** [comment]
@bendemboski @jacobq Done, just published 2.9.0!
